export const ADD_CART = 'ADD_CART'
export const REMOVE_CART = 'REMOVE_CART'
export const CART_SAVING_SHIPPING_ADDRESS = 'CART_SAVING_SHIPPING_ADDRESS'
export const CART_SAVING_PAYMENT_METHOD = 'CART_SAVING_PAYMENT_METHOD'