export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST"
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS"
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL"

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

export const ORDER_Delivery_REQUEST = 'ORDER_Delivery_REQUEST'
export const ORDER_Delivery_SUCCESS = 'ORDER_Delivery_SUCCESS'
export const ORDER_Delivery_FAIL = 'ORDER_Delivery_FAIL'
export const ORDER_Delivery_RESET = 'ORDER_Delivery_RESET'

export const MYORDER_LIST_REQUEST = 'MYORDER_LIST_REQUEST'
export const MYORDER_LIST_SUCCESS = 'MYORDER_LIST_SUCCESS'
export const MYORDER_LIST_FAIL = 'MYORDER_LIST_FAIL'
export const MYORDER_LIST_RESET = 'MYORDER_LIST_RESET'

export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST'
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS'
export const GET_ORDERS_FAIL = 'GET_ORDERS_FAIL'
export const GET_ORDERS_RESET = 'GET_ORDERS_RESET'