export const PRODUCT_LIST_LOADING = 'PRODUCT_LIST_LOADING'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAILED = 'PRODUCT_LIST_FAILED'

export const PRODUCT_DETAILS_LOADING = 'PRODUCT_DETAILS_LOADING'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAILED = 'PRODUCT_DETAILS_FAILED'

export const DELETE_PRODUCT_LOADING = 'DELETE_PRODUCT_LOADING'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL'

export const CREATE_PRODUCT_LOADING = 'CREATE_PRODUCT_LOADING'
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_FAIL = 'CREATE_PRODUCT_FAIL'
export const CREATE_PRODUCT_RESET = 'CREATE_PRODUCT_RESET'

export const UPDATE_PRODUCT_LOADING = 'UPDATE_PRODUCT_LOADING'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL'
export const UPDATE_PRODUCT_RESET = 'UPDATE_PRODUCT_RESET'

export const PRODUCT_REVIEW_LOADING = 'PRODUCT_REVIEW_LOADING'
export const PRODUCT_REVIEW_SUCCESS = 'PRODUCT_REVIEW_SUCCESS'
export const PRODUCT_REVIEW_FAIL = 'PRODUCT_REVIEW_FAIL'
export const PRODUCT_REVIEW_RESET = 'PRODUCT_REVIEW_RESET'

export const PRODUCT_CARROSEL_LOADING = 'PRODUCT_CARROSEL_LOADING'
export const PRODUCT_CARROSEL_SUCCESS = 'PRODUCT_CARROSEL_SUCCESS'
export const PRODUCT_CARROSEL_FAIL = 'PRODUCT_CARROSEL_FAIL'

export const PRODUCT_SEARCH = 'PRODUCT_SEARCH'